name: deploy notes

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build
        run: ./build.sh
      - name: Validate DEPLOY_DIR
        if: ${{ !vars.DEPLOY_DIR }}
        run: |
          echo "::error::DEPLOY_DIR is not configured"
          exit 1
      - name: deploy notes
        uses: actions/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ vars.DEPLOY_DIR }}
