name: deploy notes

on:
  workflow_dispatch:
  push:
    branchs:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: set up private key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: set up ssh config
        run: |
          echo "Host deploy"                      >> ~/.ssh/config
          echo "HostName ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
          echo "User ${{ secrets.SSH_USER }}"     >> ~/.ssh/config
          echo "ForwardAgent yes"                 >> ~/.ssh/config
          echo "IdentityFile ~/.ssh/id_rsa"       >> ~/.ssh/config
          echo "Port ${{ secrets.SSH_PORT }}"     >> ~/.ssh/config
      - name: ssh keyscan
        run: |
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: generate public
        run: |
          mkdir -p public
          for file in books media _navbar.md _sidebar.md index.html README.md
          do
            cp -r $file public
          done
      - name: deploy notes
        env:
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
        run: |
          if [ -n "$DEPLOY_DIR" ]; then
            echo "deploy to $DEPLOY_DIR"
            rsync -avz --delete -e ssh public/ deploy:${DEPLOY_DIR}
          else
            echo "vars.DEPLOY_DIR is empty"
            exit 1
          fi
      - name: setup rclone config
        env:
          KEY: ${{ secrets.CF_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          ENDPOINT: ${{ secrets.CF_ENDPOINT }}
        run: |
          rclone config create cf s3 provider Cloudflare region auto \
            no_check_bucket true \
            access_key_id ${KEY} \
            secret_access_key ${SECRET_KEY} \
            endpoint ${ENDPOINT}
      - name: deploy Cloudflare
        run: |
          rclone sync public/ cf:notes -v
