# workflow name
name: upload file to upyun storage

# master branch on push, auto run
on:
  push:
    branches:
      - master

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
    - name: download npx
      run: |
        mkdir ~/upx
        wget -P ~/upx http://collection.b0.upaiyun.com/softwares/upx/upx_0.3.5_linux_x86_64.tar.gz
        tar -xf ~/upx/upx_0.3.5_linux_x86_64.tar.gz -C ~/upx
        chmod +x ~/upx/upx

    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master

    - name: upload file to upyun storage
      env:
        UPYUN_STORAGE_KEY: ${{ secrets.UPYUN_STORAGE_KEY }}
      run: |
        file_list=$(~/upx/upx --auth $UPYUN_STORAGE_KEY ls | awk '{print $9}')
        for file in ${file_list}; do ~/upx/upx --auth $UPYUN_STORAGE_KEY rm -a $file; done

        file_list="books media _navbar.md _sidebar.md index.html README.md"
        for file in ${file_list}; do ~/upx/upx --auth $UPYUN_STORAGE_KEY put $file; done
